Import required libraries

In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Load raw data

In [6]:
df = pd.read_csv('C:\\Users\\saksh\\OneDrive\\Desktop\\AI-Cybersecurity-Project\\1_Raw_Data\\Global_Cybersecurity_Threats_2015-2024.csv')
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

Understanding The dataset

In [7]:
df.shape

(3000, 10)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              3000 non-null   object
 1   Year                                 3000 non-null   int64
 2   Attack Type                          3000 non-null   object
 3   Target Industry                      3000 non-null   object
 4   Financial Loss (in Million $)        3000 non-null   float64
 5   Number of Affected Users             3000 non-null   int64
 6   Attack Source                        3000 non-null   object
 7   Security Vulnerability Type          3000 non-null   object
 8   Defense Mechanism Used               3000 non-null   object
 9   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(3), object(6)
memory usage: 234.5+ KB

In [9]:
df.describe()

,Year,Financial Loss (in Million $),Number of Affected Users,Incident Resolution Time (in Hours)
count,3000.000000,3000.000000,3000.000000,3000.000000
mean,2019.570333,50.492970,504684.136333,36.476000
std,2.857932,28.791415,289944.084972,20.570768
min,2015.000000,0.500000,424.000000,1.000000
25%,2017.000000,25.757500,255805.250000,19.000000
50%,2020.000000,50.795000,504513.000000,37.000000
75%,2022.000000,75.630000,758088.500000,55.000000
max,2024.000000,99.990000,999635.000000,72.000000

In [10]:
df.describe(include='object')

,Country,Attack Type,Target Industry,Attack Source,Security Vulnerability Type,Defense Mechanism Used
count,3000,3000,3000,3000,3000,3000
unique,10,6,7,4,4,5
top,UK,DDoS,IT,Nation-state,Zero-day,Antivirus
freq,321,531,478,794,785,628

Check for missing values

In [11]:
df.isnull().sum()

Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

In [13]:
(df.isnull().sum()/len(df))*100

Country                                0.0
Year                                   0.0
Attack Type                            0.0
Target Industry                        0.0
Financial Loss (in Million $)          0.0
Number of Affected Users               0.0
Attack Source                          0.0
Security Vulnerability Type            0.0
Defense Mechanism Used                 0.0
Incident Resolution Time (in Hours)    0.0
dtype: float64

Handle missing values

Categorical columns

In [25]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

Numerical columns

In [26]:
numerical_cols = df.select_dtypes(include=['int64','float64']).columns

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

Check Duplicate records

In [17]:
df.duplicated().sum()
# remove duplicates if any 
# df = df.drop_duplicates()

np.int64(0)

Standardize coloumns names

In [21]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df

,country,year,attack_type,target_industry,financial_loss_(in_million_$),number_of_affected_users,attack_source,security_vulnerability_type,defense_mechanism_used,incident_resolution_time_(in_hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68
...,...,...,...,...,...,...,...,...,...,...
2995,UK,2021,Ransomware,Government,51.42,190694,Unknown,Social Engineering,Firewall,52
2996,Brazil,2023,SQL Injection,Telecommunications,30.28,892843,Hacker Group,Zero-day,VPN,26
2997,Brazil,2017,SQL Injection,IT,32.97,734737,Nation-state,Weak Passwords,AI-based Detection,30
2998,UK,2022,SQL Injection,IT,32.17,379954,Insider,Unpatched Software,Firewall,9
2999,Germany,2021,SQL Injection,Retail,48.20,480984,Unknown,Zero-day,VPN,64

Fix text formatting

In [27]:
for col in categorical_cols:
    df[col] = df[col].str.strip()

In [28]:
for col in categorical_cols:
    df[col] = df[col].str.title()

Validate DataTypes

In [29]:
df['year'] = df['year'].astype(int)

Check Unique values

In [30]:
df['country'].unique()

array(['China', 'India', 'Uk', 'Germany', 'France', 'Australia', 'Russia',
       'Brazil', 'Japan', 'Usa'], dtype=object)

In [32]:
df['attack_type'].value_counts()

attack_type
Ddos                 531
Phishing             529
Sql Injection        503
Ransomware           493
Malware              485
Man-In-The-Middle    459
Name: count, dtype: int64

Outlier Detection

In [39]:
q1 = df['financial_loss_(in_million_$)'].quantile(0.25)
q3 = df['financial_loss_(in_million_$)'].quantile(0.75)

IQR = q3 - q1
lower_bound = q1 - 1.5*IQR
upper_bound = q3 + 1.5*IQR

outliers = df[(df['financial_loss_(in_million_$)'] < lower_bound) | (df['financial_loss_(in_million_$)'] > upper_bound)]

Export clean dataset

In [40]:
df.to_csv('C:\\Users\\saksh\\OneDrive\\Desktop\\AI-Cybersecurity-Project\\4_Python_Cleaning\\cleaned_data(python).csv', index=False)